// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbQQ6aT4qk7w_nnwXzowHPS7wpP-sC1fk',
    appId: '1:871481076434:web:d6e9c4b13dcbdf84ee1b0b',
    messagingSenderId: '871481076434',
    projectId: 'tableease',
    authDomain: 'tableease.firebaseapp.com',
    databaseURL: 'https://tableease.firebaseio.com',
    storageBucket: 'tableease.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8M-jYKKdokMbFPzpNQJ8XwI4F39Krgk4',
    appId: '1:871481076434:android:94795e78bc388dfbee1b0b',
    messagingSenderId: '871481076434',
    projectId: 'tableease',
    storageBucket: 'tableease.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjF3s2cnYGgvR7UvwTKM7Mt24ysHhKbBc',
    appId: '1:871481076434:ios:b043b09b71ec5393ee1b0b',
    messagingSenderId: '871481076434',
    projectId: 'tableease',
    storageBucket: 'tableease.appspot.com',
    iosClientId: '871481076434-vqoa218ssm0e30apqlhd02omm68a301g.apps.googleusercontent.com',
    iosBundleId: 'com.revo.tableEase',
  );
}
